
SET GLOBAL event_scheduler = ON;

CREATE EVENT [IF NOT EXIST] event_name
ON SCHEDULE schedule
DO
event_body


SHOW EVENTS FROM parkinglot;

CREATE EVENT demo_event12
ON SCHEDULE AT CURRENT_TIMESTAMP()
DO
INSERT INTO DUMMY_TABLE(DUMMY_VAL) VALUES(333);


CREATE EVENT IF NOT EXISTS test_event_01
ON SCHEDULE AT CURRENT_TIMESTAMP + INTERVAL 1 MINUTE --HOUR/SECOND
on COMPLETION PRESERVE
DO
INSERT INTO DUMMY_TABLE(DUMMY_VAL) VALUES(3);


CREATE EVENT test_event_03
ON SCHEDULE EVERY 1 MINUTE
STARTS CURRENT_TIMESTAMP
ENDS CURRENT_TIMESTAMP + INTERVAL 1 HOUR
DO
INSERT INTO DUMMY_TABLE(DUMMY_VAL) VALUES(3);

drop event test_event_01 on parkinglot;